# This file was generated by GoReleaser. DO NOT EDIT.
cask "qta-ui" do
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qta-ui"

  on_macos do
    on_intel do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta-ui_v1.0.0_darwin_amd64.tar.gz"
      sha256 "b2149a05456426eaeb2e81fddf4484f4442e1c1ec8cd0f3c4a6009c0fbd7e73a"
    end
    on_arm do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta-ui_v1.0.0_darwin_arm64.tar.gz"
      sha256 "fe0a45d063c648badcf577b075d8f6a7b2d7b8695955d6cb5fb455f1fbf491cb"
    end
  end

  # No zap stanza required
end
