# This file was generated by GoReleaser. DO NOT EDIT.
cask "qta-ui" do
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qta-ui"

  on_macos do
    on_intel do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta-ui_v1.0.0_darwin_amd64.tar.gz"
      sha256 "8c3999a81ce09b5b4e9e6fd5eec9cb343f447523a6665553bbc6f7d64affe75e"
    end
    on_arm do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta-ui_v1.0.0_darwin_arm64.tar.gz"
      sha256 "7cb49097426d4ed7399318eab76095cceaa3a309a3d81359d0dec8f8d2cf1d5a"
    end
  end

  # No zap stanza required
end
