# This file was generated by GoReleaser. DO NOT EDIT.
cask "qta" do
  desc "QTA project."
  homepage "https://github.com/qta-company/qta-agent"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qta"

  on_linux do
    on_intel do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_amd64.tar.gz"
      sha256 "a095ff21e9960c4517e77fd87c0e88a9ad064e22cb8a649c1a17cb65ae4a983a"
    end
    on_arm do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_arm64.tar.gz"
      sha256 "3e79287fc0a76c7628df38acdd2bdaf80e3885386f228fb34391781a73a51e74"
    end
  end

  # No zap stanza required
end
