# This file was generated by GoReleaser. DO NOT EDIT.
cask "qta" do
  desc "QTA project."
  homepage "https://github.com/qta-company/qta-agent"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qta"

  on_linux do
    on_intel do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_amd64.tar.gz"
      sha256 "fa01f03562853367a18d8df35be63179256811992213e86f4ae92042e65d010e"
    end
    on_arm do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_arm64.tar.gz"
      sha256 "7fa9e2c0fad9d7da3673fa0e4f02666ed05b61804ea418d0c0df9cab62c230f4"
    end
  end

  # No zap stanza required
end
