# This file was generated by GoReleaser. DO NOT EDIT.
cask "qta" do
  desc "QTA project."
  homepage "https://github.com/qta-company/qta-agent"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qta"

  on_linux do
    on_intel do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_amd64.tar.gz"
      sha256 "1517e1601c9009de235957bfc976ffbc28ba4127c2c9ec57a2592e4122327b77"
    end
    on_arm do
      url "https://github.com/qta-company/qta-agent/releases/download/v1.0.0/qta_v1.0.0_linux_arm64.tar.gz"
      sha256 "897cc737dffd772e05b5c25095a689e3bae332b339fd02feca69e114bcabe3e9"
    end
  end

  # No zap stanza required
end
